image: docker:20.10.24

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  PROJECT_ID: plucky-haven-460514-g6
  REGION: us-central1
  SERVICE_NAME: backend-simulator
  REPO_NAME: backend-simulator-repo
  IMAGE_NAME: us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$SERVICE_NAME

stages:
  - deploy

before_script:
  - apk add --no-cache curl python3 py3-pip bash
  - echo "$GCP_SERVICE_KEY" > key.json
  - curl -sSL https://sdk.cloud.google.com | bash
  - source "$HOME/google-cloud-sdk/path.bash.inc"
  - gcloud auth activate-service-account --key-file=key.json
  - gcloud config set project $PROJECT_ID
  - gcloud auth configure-docker us-central1-docker.pkg.dev

deploy:
  stage: deploy
  script:
    - docker build -t $SERVICE_NAME .
    - docker tag $SERVICE_NAME $IMAGE_NAME
    - docker push $IMAGE_NAME
    - gcloud run deploy $SERVICE_NAME \
        --image $IMAGE_NAME \
        --platform managed \
        --region $REGION \
        --allow-unauthenticated \
        --port 8000
  only:
    - main
